### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by perfran** [cognitivetech/ollama-ebook-summary#12]
```
Traceback (most recent call last):
  File "C:\Users\blue\ollama-ebook-summary-main\book2text.py", line 9, in <module>
    from lib.chunking import process_csv  # Import process_csv from chunking.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blue\ollama-ebook-summary-main\lib\chunking.py", line 16, in <module>
    csv.field_size_limit(max_int)
OverflowError: Python int too large to convert to C long
```

I tried to fix this error using chatgpt.

Here is the chatgpt quote:

> You're correct to expect that the try block should catch an OverflowError and handle it by reducing the value of max_int. However, there is a subtle issue in the provided code logic:
> 
> Why the OverflowError Still Happens
> The while True loop does not properly retry after an OverflowError. Here's why:
> 
> If csv.field_size_limit(max_int) raises an OverflowError:
> 
> The except block reduces max_int.
> However, the while True loop does not reattempt csv.field_size_limit() with the reduced value. The break statement is in the try block and will always execute when no exception is raised, causing the loop to exit.
> As a result:
> 
> The code doesn't actually retry setting the limit after reducing max_int.
> Correcting the Code
> To ensure the retry mechanism works, the while True loop needs to retry setting csv.field_size_limit() with the reduced max_int in the except block.
> ```
> try:
>     max_int = sys.maxsize
>     while True:
>         try:
>             # Attempt to set the maximum field size limit
>             csv.field_size_limit(max_int)
>             break  # Break the loop if successful
>         except OverflowError:
>             # Reduce max_int and retry
>             max_int = int(max_int / 10)
> except Exception as e:
>     print(f"Unexpected error while setting field size limit: {e}")
> ```

And after making this correction in chunking.py, it seems to work :)

**Comment by cognitivetech** [comment]
oh, thanks perfran! I will review. This began here  https://github.com/cognitivetech/ollama-ebook-summary/issues/6, but I never got feedback on my initial attempt

**Comment by SolanaFox2** [comment]
I also had the same problem. The fix provided by chatgpt worked for me as well.

**Comment by cognitivetech** [comment]
oh, that's great, then I will integrate this posthaste

**Comment by cognitivetech** [comment]
I put the change as demonstrated:

```
try:
    max_int = sys.maxsize
    while True:
        try:
            # Attempt to set the maximum field size limit
            csv.field_size_limit(max_int)
            break  # Break the loop if successful
        except OverflowError:
            # Reduce max_int and retry
            max_int = int(max_int / 10)
except Exception as e:
    print(f"Unexpected error while setting field size limit: {e}")
```
we'll see :pray:
